/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;
export type JsonValue =
  | null
  | boolean
  | number
  | string
  | JsonValue[]
  | { [key: string]: JsonValue };

export type Prioridade = "alta" | "baixa" | "emergencial" | "media" | "urgente";
export type Empresa = "grupo_acontrans" | "acontrans" | "acontrans_sp" | "acseg";
export type MetodoPagamento =
  | "cartao_acseg"
  | "cartao_acontrans"
  | "cartao_sp"
  | "pix"
  | "dinheiro"
  // Compatibilidade com legado:
  | "boleto"
  | "transferencia"
  | "cartao"
  | "outro";

export type SolicitacaoStatus =
  | "rascunho"
  | "pendente_financeiro"
  | "pendente_diretoria"
  | "aprovado_para_compra"
  | "devolvido"
  | "rejeitado"
  | "em_compra"
  | "comprado"
  | "concluido"
  | "cancelado"
  | "inviavel_operacional";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole =
  | "admin"
  | "diretora_empresa"
  | "diretora_financeiro"
  | "financeiro"
  | "lider_setor"
  | "ti"
  | "user";

export interface Aprovacoes {
  aprovadorId: number;
  comentario: string | null;
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  solicitacaoId: number;
  status: string;
}

export interface Categorias {
  createdAt: Generated<Timestamp | null>;
  descricao: string | null;
  id: Generated<number>;
  nome: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface HistoricoStatus {
  comentario: string | null;
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  solicitacaoId: number;
  statusAnterior: SolicitacaoStatus | null;
  statusNovo: SolicitacaoStatus;
  usuarioId: number;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface OauthAccounts {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  provider: string;
  providerEmail: string;
  providerUserId: string;
  updatedAt: Generated<Timestamp | null>;
  userId: number;
}

export interface OauthStates {
  codeVerifier: string;
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: Generated<number>;
  provider: string;
  redirectUrl: string;
  state: string;
}

export interface NotificacoesSms {
  createdAt: Generated<Timestamp | null>;
  destinatarioNumero: string | null;
  enviadoEm: Timestamp | null;
  erro: string | null;
  evento: string;
  id: Generated<number>;
  mensagem: string;
  payloadRequisicao: ColumnType<JsonValue | null, JsonValue | null, JsonValue | null>;
  payloadResposta: ColumnType<JsonValue | null, JsonValue | null, JsonValue | null>;
  referencia: string;
  smsEmpresaCodigo: string | null;
  smsEmpresaDescricao: string | null;
  smsEmpresaId: string | null;
  smsEmpresaSituacao: string | null;
  solicitacaoId: number;
  statusEnvio: string;
  tentativaEm: Generated<Timestamp | null>;
  updatedAt: Generated<Timestamp | null>;
  usuarioId: number | null;
}

export interface NotificacoesEmail {
  assunto: string;
  createdAt: Generated<Timestamp | null>;
  destinatario: string | null;
  evento: string;
  id: Generated<number>;
  mensagemErro: string | null;
  payloadResumo: ColumnType<JsonValue | null, JsonValue | null, JsonValue | null>;
  sentAt: Timestamp | null;
  solicitacaoId: number;
  statusEnvio: string;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  userId: number;
}

export interface Setores {
  createdAt: Generated<Timestamp | null>;
  descricao: string | null;
  id: Generated<number>;
  nome: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface Solicitacoes {
  canalCompra: string | null;
  categoriaId: number;
  createdAt: Generated<Timestamp | null>;
  dataCompra: Timestamp | null;
  dataPrevistaPagamento: Timestamp | null;
  descricao: string | null;
  empresa: Empresa;
  financeiroAprovadoEm: Timestamp | null;
  financeiroAprovadoPor: number | null;
  financeiroJustificativa: string | null;
  formaPagamento: string | null;
  id: Generated<number>;
  justificativa: string;
  linkProduto: string | null;
  metodoPagamento: MetodoPagamento | null;
  observacaoCompra: string | null;
  parcelas: number | null;
  prioridade: Generated<Prioridade>;
  quantidade: Generated<number>;
  referenciaPedido: string | null;
  setorId: number;
  solicitanteId: number;
  status: Generated<SolicitacaoStatus>;
  titulo: string;
  unidade: Generated<string | null>;
  updatedAt: Generated<Timestamp | null>;
  valorEstimado: Numeric;
  valorRealCompra: Numeric | null;
  valorRealCompraUnitario: Numeric | null;
  fornecedor: string | null;
}

export interface SolicitacoesAjustesOperacionais {
  campo: string;
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  justificativa: string;
  solicitacaoId: number;
  usuarioId: number;
  valorAnterior: string | null;
  valorNovo: string | null;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  createdBy: number | null;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  id: Generated<number>;
  isActive: Generated<boolean>;
  lastLoginAt: Timestamp | null;
  mustChangePassword: Generated<boolean>;
  role: Generated<UserRole>;
  setorId: number | null;
  updatedBy: number | null;
  updatedAt: Generated<Timestamp | null>;
}

export interface DB {
  aprovacoes: Aprovacoes;
  categorias: Categorias;
  historicoStatus: HistoricoStatus;
  loginAttempts: LoginAttempts;
  notificacoesEmail: NotificacoesEmail;
  notificacoesSms: NotificacoesSms;
  oauthAccounts: OauthAccounts;
  oauthStates: OauthStates;
  sessions: Sessions;
  setores: Setores;
  solicitacoes: Solicitacoes;
  solicitacoesAjustesOperacionais: SolicitacoesAjustesOperacionais;
  userPasswords: UserPasswords;
  users: Users;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = [
  "admin",
  "diretora_empresa",
  "diretora_financeiro",
  "financeiro",
  "lider_setor",
  "ti",
  "user",
];
export const SolicitacaoStatusArrayValues: [SolicitacaoStatus, ...SolicitacaoStatus[]] = [
  "rascunho",
  "pendente_financeiro",
  "pendente_diretoria",
  "aprovado_para_compra",
  "devolvido",
  "rejeitado",
  "em_compra",
  "comprado",
  "concluido",
  "cancelado",
  "inviavel_operacional",
];
export const EmpresaArrayValues: [Empresa, ...Empresa[]] = [
  "grupo_acontrans",
  "acontrans",
  "acontrans_sp",
  "acseg",
];
  export const PrioridadeArrayValues: [Prioridade, ...Prioridade[]] = ["alta","baixa","emergencial","media","urgente"];
// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.
